version: "2"
services:
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
  backend:
    build: backend
    ports:
      - "4242:4242"
    links:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"