version: "3.3"
services:
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
  backend:
    build: backend
    links:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf