# Use a lighter version of Node as a parent image
FROM node:14.14

# Set the working directory to /api
WORKDIR /app

# copy package.json into the container at /api
COPY package.json /app

COPY . /app

# Install app dependencies
RUN npm install

# Make port 80 available to the world outside this container
EXPOSE 4242

# Run the app when the container launches
CMD ["npm", "start"]